// GENERATED by suite/refusals.py from vac/verify.py (sha256 2712172bf0ad0b94).
// Do not edit. Do not copy a name out of here into hand-written JS: address the
// table by identifier so a renamed refusal throws instead of printing a stale
// name. Regenerate with: python3 refusals.py
globalThis.VAC_REFUSALS = (function () {
  const NAMES = Object.freeze({
  ARTIFACT_UNPARSABLE: "artifact-unparsable",
  CHECK_ARTIFACT_NOT_LISTED: "check-artifact-not-listed",
  DRAFT_INCOMPLETE: "draft-incomplete",
  DUPLICATE_ARTIFACT: "duplicate-artifact",
  EMPTY_LIMITATIONS: "empty-limitations",
  EVIDENCE_UNCHECKED: "evidence-unchecked",
  INVALID_JSON: "invalid-json",
  ISSUER_COMMIT_MISMATCH: "issuer-commit-mismatch",
  MISSING_ARTIFACT: "missing-artifact",
  MISSING_ISSUER_COMMIT: "missing-issuer-commit",
  MISSING_MANIFEST: "missing-manifest",
  RAW_AGGREGATE_MISMATCH: "raw-aggregate-mismatch",
  SCHEMA_VIOLATION: "schema-violation",
  SHA256_MISMATCH: "sha256-mismatch",
  STAMP_MISMATCH: "stamp-mismatch",
  SUMMARY_MISMATCH: "summary-mismatch",
  SUMMARY_OUTRUNS_CHECKS: "summary-outruns-checks",
  UNKNOWN_PROFILE: "unknown-profile",
  UNLISTED_FILE: "unlisted-file",
  UNSAFE_ARCHIVE: "unsafe-archive",
  });
  const SOURCE = Object.freeze({"lines": 1623, "path": "vac/verify.py", "sha256": "2712172bf0ad0b94d0ce3cb075c3e01b5013f4e9678a14739b38bdf34455f148"});
  // NOT key-sorted: CRASHKIT_WEIGHTS is joined in insertion order by one
  // refusal message, so sorting it here would change the reference text.
  globalThis.VAC_SPEC = Object.freeze({"VAC_VERSION": "0.1", "PROFILES": ["certlab-bundle-v1", "fleet-board-v1", "evalmut-run-v1", "crashkit-battery-v1", "crashkit-variance-v1", "modeldrift-board-v1", "rows-aggregate-v1"], "ROW_OPS": ["count", "sum", "mean", "rate_true", "min", "max"], "CRASHKIT_WEIGHTS": {"none": 0, "low": 1, "med": 2, "high": 4, "critical": 8}, "CRASHKIT_ACC_ALIASES": ["faithfulness", "precision@k", "recall@k", "citation_rate"], "EVALMUT_HOLES": [["vacuous", "missed", "sanity"], ["blind", "missed", "kill"], ["error", "error", null], ["brittle", "flagged", null], ["coverage_gap", "missed", "diagnostic"]], "TODO_PREFIX": "TODO(", "CHECK_REFS": {"certlab-bundle-v1": ["artifact"], "fleet-board-v1": ["aggregate", "raw"], "evalmut-run-v1": ["artifact"], "crashkit-battery-v1": ["artifact"], "crashkit-variance-v1": ["artifact"], "rows-aggregate-v1": ["artifact"], "modeldrift-board-v1": ["metrics", "registry", "standings", "flips", "narrative", "results_md", "fingerprint"]}, "CHECK_OPT_REFS": {"certlab-bundle-v1": ["render"], "evalmut-run-v1": ["catalog", "render"]}, "PATTERNS": {"_CERTLAB_RENDER": "\\*\\*(\\d+)/(\\d+) seeded defects fixed\\*\\*", "_EVALMUT_RENDER": "mutation score\\s+([\\d.]+)%\\s+\\((\\d+) caught / (\\d+) applied; (\\d+) n/a\\)", "_NUMERIC_STR": "[+-]?(\\d+\\.?\\d*|\\.\\d+)([eE][+-]?\\d+)?%?"}, "REPORT_LINES": ["  proved offline: manifest schema, artifact presence + sha256, bundle closure,", "  stated limitations, stamp agreement, declared results recomputed from artifacts.", "semantic replay: NOT run by this tool. A structural PASS means the bundle is", "  internally honest, not that the issuer's grader agrees. To re-earn the", "  verdicts, run the bundle's replay block at the pinned issuer_commit:", "    (replay block unreadable \u2014 see failures above)"]});
  const R = new Proxy(NAMES, {
    get(t, k) {
      if (k === "__source") return SOURCE;
      if (k === "__names") return Object.freeze(Object.values(NAMES).slice());
      if (typeof k === "symbol" || k in t) return t[k];
      throw new Error(
        "no such refusal in the vocabulary derived from " + SOURCE.path + ": " +
        String(k) + ". The reference verifier does not emit it.");
    },
  });
  return R;
})();
if (typeof module !== "undefined" && module.exports) module.exports = globalThis.VAC_REFUSALS;
